feat(DeliveryCompany): create the DeliveryCompany model and add its r…
platanus/the-store1.2023-1 pull request #1
Opened 2022-12-27 18:51 UTC by fernandosmither

### Contexto
_the-store1_ es uno de los repositorios creados con la finalidad de introducir a los nuevos trainees, en un ambiente de onboarding técnico controlado. En particular, estoy siguiendo lo pedido en el [Notion](https://www.notion.so/platanus/Agregar-informaci-n-de-despacho-a-las-compras-3eec9a0a98184ed4ba836f7a8672577c) de requisitos.
### Qué se esta haciendo
Esta PR incluye los primeros 5 requerimientos , los cuales se basan en la creación del modelo DeliveryCompany, junto a sus relaciones y modificaciones pertinentes en la estructura de la app.
#### En particular hay que revisar
- El nuevo modelo DeliveryCompany
- Modificaciones al modelo Purchase
- Modificaciones al panel administrativo

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

2022-12-28 13:33 UTC, difernandez requested changes
Algunos detalles!

2022-12-28 13:33 UTC, difernandez commented on .gitignore
> +NOTES
este es un archivo que tu estás usando para anotarte cosas? Si es así, recomendaría agregarlo en un gitgnore global en vez de en el proyecto. La idea es que acá estén las cosas más relacionadas al proyecto más que de un setup en particular. [Acá más info](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c)

2022-12-28 13:33 UTC, difernandez commented on app/admin/delivery_companies.rb
> +  end
para los shows por lo general usamos [attributes_table](https://activeadmin.info/6-show-pages.html#:~:text=you%20can%20use-,attributes_table,-%3A), más estándar

2022-12-28 13:33 UTC, difernandez commented on app/admin/purchases.rb
> +  permit_params :status, :delivery_company, :delivery_company_id
acá solo necesitas permitir el id

2022-12-28 13:33 UTC, difernandez commented on app/models/delivery_company.rb
> +  validates :name, :phone_number, presence: true
Si se va a agregar una validación de presencia, es bueno agregar la constraint `not null` también a nivel de DB en la migración que agrega la columna

2022-12-28 14:49 UTC, fernandosmither commented on app/admin/purchases.rb
> +  permit_params :status, :delivery_company, :delivery_company_id
Resuelto, pero por qué? :O

2022-12-28 15:32 UTC, monkeyci commented on app/admin/delivery_companies.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.

2022-12-28 15:37 UTC, fernandosmither commented on app/admin/delivery_companies.rb
> +
:hocho:

2022-12-28 15:45 UTC, difernandez commented on app/admin/purchases.rb
> +  permit_params :status, :delivery_company, :delivery_company_id
Esto lo hablamos en persona, pero dejo resumen por acá:

- Para las relaciones, como `delivery_company`, se pone la relación en el input del form, pero el parámetro que se manda en la request es solo el id (`delivery_company_id`) en este caso
- El `permit_params` es un chequeo que pone explícitamente qué parámetros se van a usar en el edit/create. Osea que si yo en el form tengo `f.input :bla`, pero `:bla` no está en los `permit_params`, el valor de `bla` se va a mandar pero no se va a guardar en DB

2022-12-28 15:53 UTC, difernandez requested changes

2022-12-28 15:53 UTC, difernandez commented on app/admin/purchases.rb
> +  permit_params :delivery_company_id
aquí me refería a que no se necesitaba el `:delivery_company`, pero si se debería mantener el `status` además del id

2022-12-28 15:53 UTC, difernandez commented on db/migrate/20221226214009_create_delivery_companies.rb
> +      t.string :phone_number, null: false
acá no es suficiente agregarlo derechamente a la migración, tendrías que hacer rollback y correrla de nuevo, para que el cambio se vea reflejado en el `schema.rb` y los comentarios del modelo

2022-12-28 20:43 UTC, difernandez approved these changes
Lo veo bien 💯 recuerda pedir review a otro platanero!

2022-12-30 14:38 UTC, rjherrera reviewed
buena! se ve bien, te dejé una duda enana

2022-12-30 14:38 UTC, rjherrera commented on db/migrate/20221227133324_add_foreign_key_to_purchases.rb
> +    add_foreign_key :purchases, :delivery_companies, column: :delivery_company_id, validate: false
por qué pusiste el validate false?

2022-12-30 16:08 UTC, fernandosmither commented on db/migrate/20221227133324_add_foreign_key_to_purchases.rb
> +    add_foreign_key :purchases, :delivery_companies, column: :delivery_company_id, validate: false
Es por la gema  `strong_migrations` que pusieron en `potassium`, al añadir una referencia a una tabla ya existente, obliga a crear la validación separada, porque sino pasa a ser una migración fuerte.

![image](https://user-images.githubusercontent.com/66154723/210090039-a2a3fa43-c01a-4ddf-aae3-f0c717bf3be7.png)

Estuvimos un buen rato revisándolo con (muchas gracias) @MarcoNaik y al final cachamos que era por eso. Por ejemplo, [lacatan](https://github.com/platanus/lacatan/blob/186062976ffea85c6d3b947eb1172aa823af56fc/db/migrate/20210809194529_add_foreign_key_to_users.rb).

2022-12-30 16:09 UTC, fernandosmither commented on db/migrate/20221227133324_add_foreign_key_to_purchases.rb
> +    add_foreign_key :purchases, :delivery_companies, column: :delivery_company_id, validate: false
Ps. Si estás de acuerdo con esto, lo agregaría a alguna guía o FAQ interno que no sé si tengamos, pero me imagino que es un error común jeje

2022-12-30 16:15 UTC, rjherrera approved these changes

2022-12-30 16:16 UTC, rjherrera commented on db/migrate/20221227133324_add_foreign_key_to_purchases.rb
> +    add_foreign_key :purchases, :delivery_companies, column: :delivery_company_id, validate: false
buena! perfect, buena idea, igual lo de strong migrations es como una guía para hacerlo, habrá que especificarlo en algún lado nuestro tu deci?

2022-12-30 17:27 UTC, fernandosmither commented on db/migrate/20221227133324_add_foreign_key_to_purchases.rb
> +    add_foreign_key :purchases, :delivery_companies, column: :delivery_company_id, validate: false
Esque más que una guía, la gema tira error cuando intentas hacer una migración fuerte y no te deja. Ahí lo repliqué sacándole el `validate: false` para que se vea

![image](https://user-images.githubusercontent.com/66154723/210097135-42acec65-33a8-4236-bdea-a364b6be33d2.png)

2022-12-30 17:29 UTC, rjherrera commented on db/migrate/20221227133324_add_foreign_key_to_purchases.rb
> +    add_foreign_key :purchases, :delivery_companies, column: :delivery_company_id, validate: false
sí sí, de hecho ese es el comportamiento deseado de la gema jaja, a lo que voy es que no cacho qué cosa iría en la guía que deci, sería como parecido a lo que dice el readme de strong migrations o no?

2022-12-30 17:30 UTC, fernandosmither commented on db/migrate/20221227133324_add_foreign_key_to_purchases.rb
> +    add_foreign_key :purchases, :delivery_companies, column: :delivery_company_id, validate: false
Lo otro, aquí el mensaje de error tiró todas las instrucciones, pero cuando me pasó el error por primera vez no sucedió así, porque era necesario añadir la línea que nunca había visto `disable_ddl_transaction!`, que si no fuera por el gran @MarcoNaik nunca habría cachado jajaja (se debe agregar al `add_reference`, y luego crear la foreign key y luego la validación

![image](https://user-images.githubusercontent.com/66154723/210097402-106a66d5-12bf-43b6-ac5b-0addcf21bb6a.png)

2022-12-30 17:40 UTC, merged