feat(purchases-view): add fully featured show for purchases
platanus/the-store1.2023-1 pull request #12
Opened 2023-01-12 21:02 UTC by fernandosmither

### Contexto
the-store1 es uno de los repositorios creados con la finalidad de introducir a los nuevos trainees, en un ambiente de onboarding técnico controlado. En particular, estoy siguiendo lo pedido en el [Notion](https://www.notion.so/platanus/Agregar-informaci-n-de-despacho-a-las-compras-3eec9a0a98184ed4ba836f7a8672577c) de requisitos.

### Qué se esta haciendo
Esta PR añade todas las funcionalidades pedidas de `frontend`, junto a mejoras menores.
#### En particular hay que revisar
Que se cumplan los siguientes checks:

![image](https://user-images.githubusercontent.com/66154723/212180328-0ff32c97-174d-47c1-96b6-df22f1abad7d.png)

[Figma](https://www.figma.com/file/TUBICpcfyhq9ZkNRXTwJhx/Proyecto-Trainees---Tienda-de-muebles?node-id=188%3A3625&t=hdQzDyJzKxXvaJ2B-0)

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)

![image](https://user-images.githubusercontent.com/66154723/212180506-bc6bfcc8-2a2b-4a52-9f08-89d0ca59d914.png)

![image](https://user-images.githubusercontent.com/66154723/212180482-74db01e6-5739-41db-a6a2-548e883210b0.png)

![image](https://user-images.githubusercontent.com/66154723/212180570-c75366a5-a4b0-4b30-b40b-0ee4ff09f933.png)

2023-01-12 21:03 UTC, monkeyci commented on app/serializers/api/internal/delivery_company_serializer.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.

2023-01-12 21:04 UTC, monkeyci commented on app/javascript/components/purchase-detail.vue
> +    console.log(request.data);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement  no-console

2023-01-12 21:04 UTC, monkeyci commented on app/controllers/api/internal/purchases_controller.rb
> +    purchase.update!(purchase_params)
<sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not covered lines: 17 and 18

2023-01-13 14:55 UTC, nicolasguridi requested changes
te dejé algunos comentarios! el resto está bien

sobre los commits mismos:
- en la [guía](https://la-guia.platan.us/setup/configuracion_de_proyectos/git#tipo) dice que se usa `chore` como tipo del commit cuando se hacen "cambios al proceso de build y herramientas auxiliares", pero el primer commit no hace nada de eso. Lo renombraría a `feat` o `refactor`
- intenta dejar todos los cambios sobre un archivo en un mismo commit. Hace una diferencia gigante en la facilidad de corregir el PR después
- trata de que cada commit tenga cambios relacionados entre sí. Por ejemplo, si actualizas la versión de una librería y luego cambias un controlador de vista que no usa directamente esa librería, mejor que vayan en commits separados
- en general evitamos hacer commits con fixes a cosas que cambiamos en el mismo PR, como en el último commit. Usamos --fixup para que la historia quede más limpia. [Aquí](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument) hay unos links donde se explica cómo hacerlo y por qué lo hacemos así

me parece que una buena medida sería rehacer los commits para ir practicando ahora en un ambiente seguro 😅 , cualquier duda pregúntame nomás

2023-01-13 14:55 UTC, nicolasguridi commented on app/javascript/components/purchase-detail.vue
> +  {{ dateFormatter(purchase.createdAt) }}
podrías guardar esta información dentro de variables para no repetir el formateo en dos partes diferentes del html. Así, si por ejemplo más adelante quisieras cambiar el `$` por un `CLP` solo tendrías que cambiarlo en un lugar y evitarías el riesgo de que lo cambies en uno y se te olvide el otro

2023-01-13 14:55 UTC, nicolasguridi commented on app/javascript/components/purchase-list-card.vue
> +  purchase: Purchase
buen cambio este! me hace sentido agrupar las props si todas pertenecen al mismo objeto

2023-01-13 14:55 UTC, nicolasguridi commented on app/javascript/components/purchase-detail.vue
> +  return dateStr;
por qué terminaste no usando `useDateFormat`?

2023-01-13 14:55 UTC, nicolasguridi commented on app/javascript/api/purchases.ts
> +  reschedule(purchaseId: number, deliveryDate: string) {
por qué nombrar `reschedule` a este endpoint? me parece que `update` es un mejor nombre, así quedaría más general porque a futuro podrías querer actualizar más atributos de la compra. Además es más fácil mapearlo a los métodos del controlador en el back

2023-01-13 14:55 UTC, nicolasguridi commented on app/javascript/components/purchase-detail.vue
> +    parseInt(dateArray[DAY_INDEX], 10));
por qué no usar un Date de javascript para esto? en general parsear fechas "a mano" es muy propenso a errores. Podrías usar un datepicker también, para facilitar el ingreso de la fecha por parte del usuario. Hay varios proyectos en platanus que lo tienen, por si necesitas inspiración 👀

2023-01-13 16:17 UTC, fernandosmither commented on app/javascript/components/purchase-detail.vue
> +    parseInt(dateArray[DAY_INDEX], 10));
A qué te refieres con lo de Date de javascript? Lo terminé haciendo así porque el formato es dd/mm/yyyy, y el por defecto es mm/dd/yyyy, hay una forma más limpia de implementar esto?

Lo del datepicker, definitivamente! Pero seguí el figma al pie de la letra, y tenía que ser un text input :thinking:

2023-01-13 16:20 UTC, fernandosmither commented on app/javascript/components/purchase-detail.vue
> +  return dateStr;
Funcionó muy bien, excepto en la parte final de hacer display de texto. Resulta que el figma lo pedía así:

![image](https://user-images.githubusercontent.com/66154723/212368220-38a31d09-d383-4877-9aa9-15a6868d4672.png)

Pero `useDateFormat` lo tiraba en inglés, y con detalles, como una coma, y la primera letra sin mayúsculas. Le dí media hora y en las issues de la lib encontré que no había forma fácil de traducirlo y que se escapaba del propósito de la lib, y @rjherrera sugirió usar `Intl.DateTimeFormat`, pero si se puede configurar fácil el `useDateFormat` y ocreo que mejor, porque queda el código más limpio!

2023-01-13 17:29 UTC, nicolasguridi commented on app/javascript/components/purchase-detail.vue
> +    parseInt(dateArray[DAY_INDEX], 10));
sí! con `date-fns` que es una librería bien buena para el manejo de fechas. Tiene esta función [parse](https://date-fns.org/v2.29.3/docs/parse) que te permite pasarle el formato en que viene la fecha y te retorna un objeto de tipo Date, así:
```
result = parse('02/11/2014', 'dd/MM/yyyy', new Date())
```

Sobre eso de que sea un text input, he visto proyectos en que el input es ambas cosas a la vez:

https://user-images.githubusercontent.com/42162243/212380299-afa006e4-8158-4e76-a228-0e4280c87d31.mov

Lo dejaría como text input nomás, pero si parsearía la fecha con la función que te mandé más arriba

2023-01-13 17:31 UTC, nicolasguridi commented on app/javascript/components/purchase-detail.vue
> +  return dateStr;
probaste usando los [locales](https://vueuse.org/shared/usedateformat/#use-with-locales)?

2023-01-13 18:40 UTC, fernandosmither commented on app/javascript/components/purchase-detail.vue
> +  return dateStr;
Sii, pero ahí persistía el problema de que le añadía una coma y estaba en minúsculas

2023-01-13 18:56 UTC, difernandez commented on app/javascript/components/purchase-detail.vue
> +    parseInt(dateArray[DAY_INDEX], 10));
podrías probar poniéndole `type="date"` al input, con eso te debería quedar pa texto y con datepicker

2023-01-13 19:53 UTC, difernandez requested changes
buena! dejo algunos comentarios, el de item-details creo que es el más importante, los otros son más piolas u opcionales

2023-01-13 19:53 UTC, difernandez commented on app/javascript/components/purchase-list-card.vue
> +      :src="require('assets/images/right_arrow.svg').default"
duda: necesitas el `.default`? creo que no lo había visto antes

2023-01-13 19:53 UTC, difernandez commented on app/controllers/app/purchases_controller.rb
> +  end
en controllers de app (no api digamos) encuentro que queda raro usar el patrón de memoization (el método `purchase` con el `||=`) y después llamarlo en la action, `show` en este caso. Esto porque en api semánticamente hace sentido el `respond_with purchase` => estás diciendo que ese método tiene que responder con esa purchase. En cambio en estos controllers no se usa algo como el `respond_with bla`, entonces un `purchase` suelto no está comunicando mucho, es solo una "cosa" no una "frase", no se si me explico jaja.
Lo que haría en estos casos es una de estas dos opciones:
- no tener método extra, y solo llamar directo a `@purchase = current_user.purchases.find(purchase_params[:id])` en el show
- Tener método extra, pero sin memoization y que sea un verbo, que indique que es lo que se está haciendo:
```ruby
  def set_purchase
    @purchase = current_user.purchases.find(purchase_params[:id])
  end
```

Qué opinas?

2023-01-13 19:53 UTC, difernandez commented on app/javascript/application.js
> +import ItemDetail from './components/item-detail.vue';
Este cambio de nombre no corresponde este pr, es un componente de otro pitch. De hecho, con esto probablemente se rompió [la vista del `items#show`](https://github.com/platanus/the-store1/blob/master/app/views/app/items/show.html.erb), ya que ahí está con `item-show-detail`

2023-01-13 19:53 UTC, difernandez commented on app/controllers/app/purchases_controller.rb
> +      [:item, :delivery_company]
no es necesario que estén en un array, pueden estar ambos "sueltos"

2023-01-13 19:53 UTC, difernandez commented on app/javascript/components/purchase-detail.vue
> +            Total: {{ MONEY_DENOMINATOR }}{{ purchase.item.price }}
Porque cambiar esto y sacarlo a una constante?

2023-01-13 19:53 UTC, difernandez commented on app/javascript/components/purchase-detail.vue
> +      <div class="">
sacaría el class si estaría vacío

2023-01-13 19:53 UTC, difernandez commented on app/javascript/components/purchase-detail.vue
> +      v-show="!showReschedule"
por lo general usamos poco el `v-show`, favorecemos más el `v-if` por lo que he visto. No estoy seguro porque, supongo que más costumbre, pero el beneficio que tiene y que calza con este uso, es que puedes usar `v-else-if` y `v-else`, que te serviría pa la siguiente section

2023-01-13 19:53 UTC, difernandez commented on app/javascript/components/purchase-detail.vue
> +              <p class="mx-4 my-2 text-lg font-bold text-white">
me parece que no es necesario este `<p>`, el texto puede ir directo dentro del `button`, y en vez de `margin` usar `padding` pa los espaciados, y las demás clases directo en el botón

2023-01-13 20:01 UTC, fernandosmither commented on app/controllers/app/purchases_controller.rb
> +  end
Toda la razón master!

2023-01-13 20:12 UTC, nicolasguridi approved these changes
Quedó mucho mejor la separación y el orden de los commits! 💯 
Te dejé una sugerencia nomás, por si te tinca

2023-01-13 20:12 UTC, nicolasguridi commented on app/javascript/components/purchase-detail.vue
> +  let dateStr = format(new Date(date), "EEEE d 'de' LLLL", { locale: es });
el argumento `type` podría ser el formato que le pasas a `format` (por ejemplo `'dd/MM/yyyy'`). Así podrías simplificar la función:
```
function dateFormatter(date: Date, type = 'dd/MM/yyyy'): string {
  const formattedDate = format(new Date(date), type, { locale: es });
  const uppercasedDate = (dateStr.charAt(0).toUpperCase() + dateStr.slice(1));

  return uppercasedDate
}

2023-01-16 14:09 UTC, fernandosmither commented on app/javascript/components/purchase-detail.vue
> +            Total: {{ MONEY_DENOMINATOR }}{{ purchase.item.price }}
Fue una sugerencia de Nico que apuntaba a si se cambia en el futuro, sería más fácil cambiarlo en solo un lugar

2023-01-16 14:14 UTC, fernandosmither commented on app/javascript/components/purchase-detail.vue
> +              <p class="mx-4 my-2 text-lg font-bold text-white">
Tremendo, mucho más limpio!

2023-01-16 14:18 UTC, fernandosmither commented on app/javascript/components/purchase-detail.vue
> +  let dateStr = format(new Date(date), "EEEE d 'de' LLLL", { locale: es });
Genial sugerencia!!! Gracias

2023-01-16 15:01 UTC, difernandez requested changes

2023-01-16 15:01 UTC, difernandez commented on app/javascript/application.js
> +import PurchaseDetail from './components/purchase-detail.vue';
Faltó revertir esto de los items que viene del otro pitch, acá y abajo en `components`

2023-01-16 15:23 UTC, fernandosmither commented on app/javascript/application.js
> +import PurchaseDetail from './components/purchase-detail.vue';
Ahí sí!!!

2023-01-16 15:30 UTC, difernandez approved these changes
buenaa 🚀

2023-01-17 12:45 UTC, merged