feat(purchase-validations): validate params
platanus/the-store1.2023-1 pull request #4
Opened 2022-12-30 19:41 UTC by fernandosmither

### Contexto
En una PR anterior se creó la clase `DeliveryCompany`, la cual se anexó a `Purchase`, y por ende, la última recibió varios cambios que deben ser validados, como se menciona en la sección de _Nice to have_ del proyecto sandbox.
### Qué se esta haciendo
Esta PR incluye todas las validaciones pertinentes, junto a factories y testing.
#### En particular hay que revisar
Que se cumpla la siguiente lista:

![image](https://user-images.githubusercontent.com/66154723/210106608-1287b677-a9bd-414b-a08e-71cc2d8d0def.png)

2022-12-30 20:01 UTC, gmq commented on app/models/purchase.rb
> +  validates :delivery_date, presence: true, if: :delivered?
Puedes consolidar las dos validaciones que dependen de `delivered?` en una

`validates :delivery_date, :delivery_company, presence: true, if: :delivered?`

2022-12-30 20:01 UTC, gmq commented on app/models/purchase.rb
> +  def delivered?
No debería ser necesario esto, al usar enums Rails automáticamente crea helpers con `?` al final
https://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html

2022-12-30 20:32 UTC, ldlsegovia requested changes

2022-12-30 20:32 UTC, ldlsegovia commented on spec/models/purchase_spec.rb
> +  describe 'validations' do
Con la forma en que hiciste los tests los contextos son meramente descriptivos y no están cambiando nada de tu escenario original. Te propongo esta alternativa que va cambiando en cada contexto alguna cosa. Me cuentas que te parece

```ruby
  describe 'validations' do
    let(:delivery_company) { nil }
    let(:deliver_date) { nil }
    let(:status) { :pending }

    let(:purchase) do
      build(
        :purchase,
        delivery_company: delivery_company,
        deliver_date: deliver_date,
        status: status
      )
    end

    it { expect(purchase).not_to validate_presence_of(:delivery_date) }
    it { expect(purchase).not_to validate_presence_of(:delivery_company) }

    context 'with delivery company' do
      let(:delivery_company) { create(:delivery_company) }

      it { expect(purchase).to validate_presence_of(:delivery_date) }
      it { expect(purchase).to validate_presence_of(:delivery_company) }

      context "with delivery date in the past" do
        let(:deliver_date) { 1.day.ago }

        it { expect(purchase).not_to be_valid }
      end

      context "with delivery date in the future" do
        let(:deliver_date) { 1.day.from_now }

        it { expect(purchase).to be_valid }
      end
    end

    context 'with delivered status' do
      let(:status) { :delivered }

      it { expect(purchase).to validate_presence_of(:delivery_date) }
      it { expect(purchase).to validate_presence_of(:delivery_company) }
    end
  end
```

2023-01-03 14:50 UTC, fernandosmither commented on app/models/purchase.rb
> +  def delivered?
10/10 GENIAL!! Justo buscaba algo así!! :rocket:

2023-01-03 16:05 UTC, fernandosmither commented on spec/models/purchase_spec.rb
> +  describe 'validations' do
Genial! Muchas gracias por toda tu ayuda.

2023-01-03 16:18 UTC, ldlsegovia approved these changes

2023-01-03 16:20 UTC, gmq approved these changes

2023-01-03 16:23 UTC, merged